server:
  port: 8081
spring:
  application:
    name: board-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:mysql://localhost:3306/board_app?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    com.example.spring.boardservice: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  swagger-ui:
    path: /swagger-ui.html

file:
  upload-dir: ./uploads
