server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: native # 파일시스템 백엔드 - config-repo 폴더의 yml을 "그대로" 서빙(git 불필요)
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/lect/msa/config-repo
# curl localhost:8888/{서비스이름}/{프로필}
# curl localhost:8888/auth-service/default
# curl localhost:8888/application/default